### PR TITLE
Draft: Add support for write operations

### LINKED ISSUE #2: Set commands
Would it be possible to add the set property, so that values can be written back to vcontrold?

### PR DESCRIPTION
**Pull request by winnieXY**
Add the possibility to write data back to vcontrold. This will close #2

### CODE REVIEW

**Comment by winnieXY** [comment]
This will close #2

**Review by euweb — CHANGES_REQUESTED** [review]
would you please remove pyvclient.pyproj file, since many people using different editors/IDEs

**Comment by winnieXY** [comment]
Yepp, I'll do  this afternoon. This file shouldn't go into the merge request

**Comment by winnieXY** [comment]
I would wait with merging. The code seems to work now in regards to locking - however from time to time pyvclient hangs up an no new data is requested from vcontrold and submitted to mqtt. I'm not sure if this is related to this merge request yet.

**Comment by winnieXY** [comment]
I'm getting these errors into the error file on a regular basis:


ERROR <PID 7821:MainProcess> pyvclient.vcomm.vcomm.set_command(): 'NoneType' object has no attribute 'sendall'
ERROR <PID 7821:MainProcess> pyvclient.vcomm.vcomm.__request(): 'NoneType' object has no attribute 'recv'

Any idea why? As mentioned before, I'm not that familiar with python. C#,C and C++ are more familiar for me ;)

**Comment by winnieXY** [comment]
> 
> 
> I'm getting these errors into the error file on a regular basis:
> 
> ERROR <PID 7821:MainProcess> pyvclient.vcomm.vcomm.set_command(): 'NoneType' object has no attribute 'sendall'
> ERROR <PID 7821:MainProcess> pyvclient.vcomm.vcomm.__request(): 'NoneType' object has no attribute 'recv'
> 
> Any idea why? As mentioned before, I'm not that familiar with python. C#,C and C++ are more familiar for me ;)

Fixed it. This was a locking/releasing issue + unprecise while loop condition.

**Review by euweb — APPROVED** [review]

**Pull request merged**
